import type { Book, Checkout, User, Category, Review } from './types';

// Expanded sample data for demonstration
// Users: 35+ realistic users with proper UAT student format
export const expandedUsers: Omit<User, 'id'>[] = [
    // Librarian
    { 
        username: 'admin', 
        password: 'admin', 
        role: 'librarian',
        name: 'Dra. Carmen Elizondo',
        email: 'celizondo@uat.edu.mx',
        curp: 'ELIC850315MDFZRM03',
        phone: '834-318-1800',
        address: 'UAT, Centro Universitario Victoria',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=admin',
        bannerUrl: 'https://picsum.photos/seed/banner-admin/1200/300',
        bio: 'Directora de la Biblioteca Central UAT. 20 años de experiencia en ciencias de la información. Especialista en recursos digitales y gestión de colecciones.',
        favoriteBooks: [],
        following: [],
        followers: [],
        createdAt: '2020-01-15T10:00:00.000Z',
    },

    // Engineering Students
    { 
        username: 'a1234567890', 
        password: 'password',
        role: 'client',
        name: 'Juan Carlos Pérez Hernández',
        curp: 'PERJ020315HDFRMN02',
        phone: '834-112-3456',
        email: 'a1234567890@alumnos.uat.edu.mx',
        address: 'Col. Revolución, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a1234567890',
        bannerUrl: 'https://picsum.photos/seed/banner-1/1200/300',
        bio: '📚 Ingeniería en Sistemas Computacionales | Semestre 7 | Aficionado a la ciencia ficción y la programación. Me fascina leer sobre IA y robótica.',
        badgeLabel: '🎮 Gamer & Bookworm 📚',
        favoriteBooks: [],
        following: ['a0987654321', 'a2345678901'],
        followers: ['a0987654321', 'a3456789012'],
        books_read: 15,
        createdAt: '2023-08-20T11:30:00.000Z',
    },
    
    { 
        username: 'a0987654321', 
        password: 'password', 
        role: 'client',
        name: 'María Elena Rodríguez López',
        curp: 'ROLM010822MDFDRN05',
        phone: '834-223-4567',
        email: 'a0987654321@alumnos.uat.edu.mx',
        address: 'Col. Guadalupe, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a0987654321',
        bannerUrl: 'https://picsum.photos/seed/banner-2/1200/300',
        bio: '🔬 Ingeniería Química | Semestre 5 | Lectora voraz de novela histórica y biografías. Presidenta del Club de Lectura UAT.',
        badgeLabel: '☕ Coffee & Books lover',
        favoriteBooks: [],
        following: ['a1234567890', 'a2345678901', 'a4567890123'],
        followers: ['a1234567890', 'a2345678901', 'a5678901234'],
        books_read: 28,
        createdAt: '2023-01-10T09:15:00.000Z',
    },

    { 
        username: 'a2345678901', 
        password: 'password',
        role: 'client',
        name: 'Luis Fernando García Martínez',
        curp: 'GAML990205HDFRTL01',
        phone: '834-334-5678',
        email: 'a2345678901@alumnos.uat.edu.mx',
        address: 'Col. Pedro Sosa, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a2345678901',
        bannerUrl: 'https://picsum.photos/seed/banner-3/1200/300',
        bio: '⚙️ Ingeniería Mecánica | Semestre 6 | Entusiasta de libros técnicos y novelas de aventuras. Miembro activo del taller de robótica.',
        favoriteBooks: [],
        following: ['a0987654321', 'a3456789012'],
        followers: ['a1234567890', 'a0987654321', 'a4567890123'],
        books_read: 12,
        createdAt: '2023-02-14T14:20:00.000Z',
    },

    // Business/Administration Students
    { 
        username: 'a3456789012', 
        password: 'password',
        role: 'client',
        name: 'Ana Sofía Martínez Vásquez',
        curp: 'MAVA000918MDFRSN07',
        phone: '834-445-6789',
        email: 'a3456789012@alumnos.uat.edu.mx',
        address: 'Col. Morelos, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a3456789012',
        bannerUrl: 'https://picsum.photos/seed/banner-4/1200/300',
        bio: '💼 Lic. en Administración de Empresas | Semestre 4 | Apasionada por los libros de liderazgo y desarrollo personal.',
        badgeLabel: '💼 Future CEO',
        favoriteBooks: [],
        following: ['a4567890123', 'a5678901234'],
        followers: ['a1234567890', 'a2345678901', 'a6789012345'],
        books_read: 19,
        createdAt: '2023-03-05T16:45:00.000Z',
    },

    { 
        username: 'a4567890123', 
        password: 'password',
        role: 'client',
        name: 'Roberto Carlos Jiménez Torres',
        curp: 'JITR010703HDFMRB04',
        phone: '834-556-7890',
        email: 'a4567890123@alumnos.uat.edu.mx',
        address: 'Col. Azteca, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a4567890123',
        bannerUrl: 'https://picsum.photos/seed/banner-5/1200/300',
        bio: '📊 Lic. en Contaduría Pública | Semestre 8 | Lector de libros de finanzas, economía y novelas de misterio.',
        favoriteBooks: [],
        following: ['a3456789012', 'a5678901234', 'a7890123456'],
        followers: ['a0987654321', 'a2345678901', 'a8901234567'],
        books_read: 23,
        createdAt: '2023-01-28T12:10:00.000Z',
    },

    // Psychology/Social Sciences Students  
    { 
        username: 'a5678901234', 
        password: 'password',
        role: 'client',
        name: 'Paola Fernanda Sánchez Ruiz',
        curp: 'SARP990612MDFNRL02',
        phone: '834-667-8901',
        email: 'a5678901234@alumnos.uat.edu.mx',
        address: 'Col. Las Flores, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a5678901234',
        bannerUrl: 'https://picsum.photos/seed/banner-6/1200/300',
        bio: '🧠 Lic. en Psicología | Semestre 6 | Amo la literatura psicológica y las novelas que exploran la mente humana.',
        favoriteBooks: [],
        following: ['a6789012345', 'a7890123456'],
        followers: ['a3456789012', 'a4567890123', 'a9012345678'],
        books_read: 31,
        createdAt: '2023-04-12T08:30:00.000Z',
    },

    { 
        username: 'a6789012345', 
        password: 'password',
        role: 'client',
        name: 'Diego Alejandro Morales Castro',
        curp: 'MOCD010429HDFRSN03',
        phone: '834-778-9012',
        email: 'a6789012345@alumnos.uat.edu.mx',
        address: 'Col. Loma Real, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a6789012345',
        bannerUrl: 'https://picsum.photos/seed/banner-7/1200/300',
        bio: '📖 Lic. en Ciencias de la Comunicación | Semestre 7 | Periodista en formación. Leo de todo: desde clásicos hasta ciencia ficción.',
        favoriteBooks: [],
        following: ['a5678901234', 'a8901234567'],
        followers: ['a3456789012', 'a7890123456', 'a0123456789'],
        books_read: 26,
        createdAt: '2023-02-28T15:50:00.000Z',
    },

    // Medical/Health Sciences Students
    { 
        username: 'a7890123456', 
        password: 'password',
        role: 'client',
        name: 'Valeria Isabel Cruz Mendoza',
        curp: 'CUMV000308MDFRNL06',
        phone: '834-889-0123',
        email: 'a7890123456@alumnos.uat.edu.mx',
        address: 'Col. Ampliación Revolución, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a7890123456',
        bannerUrl: 'https://picsum.photos/seed/banner-8/1200/300',
        bio: '⚕️ Medicina | Semestre 3 | Futura doctora con pasión por la literatura médica y los thrillers psicológicos.',
        favoriteBooks: [],
        following: ['a8901234567', 'a9012345678'],
        followers: ['a4567890123', 'a5678901234', 'a1234567890'],
        books_read: 14,
        createdAt: '2023-05-20T10:25:00.000Z',
    },

    { 
        username: 'a8901234567', 
        password: 'password',
        role: 'client',
        name: 'Andrés Mateo Herrera Solís',
        curp: 'HESA991015HDFRLND01',
        phone: '834-990-1234',
        email: 'a8901234567@alumnos.uat.edu.mx',
        address: 'Col. Tamatan, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a8901234567',
        bannerUrl: 'https://picsum.photos/seed/banner-9/1200/300',
        bio: '🏥 Lic. en Enfermería | Semestre 5 | Interesado en literatura médica, autoayuda y novelas de drama.',
        favoriteBooks: [],
        following: ['a7890123456', 'a0123456789'],
        followers: ['a4567890123', 'a6789012345', 'a2345678901'],
        books_read: 17,
        createdAt: '2023-03-15T13:40:00.000Z',
    },

    // Law Students
    { 
        username: 'a9012345678', 
        password: 'password',
        role: 'client',
        name: 'Isabella Carmen Delgado Reyes',
        curp: 'DERI010125MDFLYN08',
        phone: '834-001-2345',
        email: 'a9012345678@alumnos.uat.edu.mx',
        address: 'Col. Jardín, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a9012345678',
        bannerUrl: 'https://picsum.photos/seed/banner-10/1200/300',
        bio: '⚖️ Derecho | Semestre 9 | Próxima abogada especializada en derechos humanos. Amo la literatura jurídica y los clásicos.',
        favoriteBooks: [],
        following: ['a0123456789', 'a1234567890'],
        followers: ['a5678901234', 'a7890123456', 'a3456789012'],
        books_read: 35,
        createdAt: '2022-08-10T07:15:00.000Z',
    },

    // More diverse students...
    { 
        username: 'a0123456789', 
        password: 'password',
        role: 'client',
        name: 'César Augusto Ramírez Flores',
        curp: 'RAFC000720HDFMLR09',
        phone: '834-112-3457',
        email: 'a0123456789@alumnos.uat.edu.mx',
        address: 'Col. Francisco Villa, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a0123456789',
        bannerUrl: 'https://picsum.photos/seed/banner-11/1200/300',
        bio: '🎨 Lic. en Diseño Gráfico | Semestre 4 | Creativo apasionado por el arte, la fotografía y los cómics.',
        favoriteBooks: [],
        following: ['a2468135790', 'a1357924680'],
        followers: ['a6789012345', 'a8901234567', 'a4567890123'],
        books_read: 8,
        createdAt: '2023-06-30T17:20:00.000Z',
    },

    // Additional students for variety...
    { 
        username: 'a2468135790', 
        password: 'password',
        role: 'client',
        name: 'Fernanda Cristina Aguilar Nava',
        curp: 'AGNF010816MDFGVR04',
        phone: '834-224-6810',
        email: 'a2468135790@alumnos.uat.edu.mx',
        address: 'Col. Miguel Alemán, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a2468135790',
        bannerUrl: 'https://picsum.photos/seed/banner-12/1200/300',
        bio: '🌱 Ing. en Desarrollo Sustentable | Semestre 2 | Defensora del medio ambiente, leo sobre ecología y sostenibilidad.',
        favoriteBooks: [],
        following: ['a1357924680', 'a9876543210'],
        followers: ['a0123456789', 'a5678901234'],
        books_read: 6,
        createdAt: '2023-08-28T19:45:00.000Z',
    },

    // Continue with more students to reach 30+
    { 
        username: 'a1357924680', 
        password: 'password',
        role: 'client',
        name: 'Emiliano Jesús Vargas Cortés',
        curp: 'VACE990402HDFRRM01',
        phone: '834-135-7924',
        email: 'a1357924680@alumnos.uat.edu.mx',
        address: 'Col. Benito Juárez, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a1357924680',
        bannerUrl: 'https://picsum.photos/seed/banner-13/1200/300',
        bio: '🏃‍♂️ Lic. en Ciencias del Deporte | Semestre 6 | Atleta y lector de biografías deportivas y libros de motivación.',
        favoriteBooks: [],
        following: ['a9876543210', 'a8642097531'],
        followers: ['a2468135790', 'a0123456789'],
        books_read: 11,
        createdAt: '2023-04-18T11:00:00.000Z',
    },

    { 
        username: 'a9876543210', 
        password: 'password',
        role: 'client',
        name: 'Camila Alejandra Ortega Domínguez',
        curp: 'ORDC010912MDFRMM05',
        phone: '834-987-6543',
        email: 'a9876543210@alumnos.uat.edu.mx',
        address: 'Col. Libertad, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a9876543210',
        bannerUrl: 'https://picsum.photos/seed/banner-14/1200/300',
        bio: '🍳 Lic. en Gastronomía | Semestre 7 | Chef en formación, colecciono libros de cocina internacional y novelas románticas.',
        favoriteBooks: [],
        following: ['a8642097531', 'a7531902468'],
        followers: ['a1357924680', 'a2468135790'],
        books_read: 22,
        createdAt: '2022-11-22T14:30:00.000Z',
    },

    // Continue adding more students with different backgrounds
    { 
        username: 'a8642097531', 
        password: 'password',
        role: 'client',
        name: 'Santiago Rafael Moreno Paz',
        curp: 'MOPS000528HDFRZN02',
        phone: '834-864-2097',
        email: 'a8642097531@alumnos.uat.edu.mx',
        address: 'Col. Tancol, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a8642097531',
        bannerUrl: 'https://picsum.photos/seed/banner-15/1200/300',
        bio: '🎵 Lic. en Música | Semestre 5 | Músico profesional, aficionado a biografías de compositores y novela histórica.',
        favoriteBooks: [],
        following: ['a7531902468', 'a6420975318'],
        followers: ['a9876543210', 'a1357924680'],
        books_read: 18,
        createdAt: '2023-01-07T09:20:00.000Z',
    },

    // Add more diverse students
    { 
        username: 'a7531902468', 
        password: 'password',
        role: 'client',
        name: 'Ximena Guadalupe Contreras Silva',
        curp: 'COSX010214MDFNLM07',
        phone: '834-753-1902',
        email: 'a7531902468@alumnos.uat.edu.mx',
        address: 'Col. Vicente Guerrero, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a7531902468',
        bannerUrl: 'https://picsum.photos/seed/banner-16/1200/300',
        bio: '🌐 Lic. en Idiomas | Semestre 8 | Políglota en formación, amo la literatura mundial y los libros en diferentes idiomas.',
        favoriteBooks: [],
        following: ['a6420975318', 'a5319246807'],
        followers: ['a8642097531', 'a9876543210'],
        books_read: 29,
        createdAt: '2022-09-15T16:10:00.000Z',
    },

    // Continue with more students to reach 30+ total
    { 
        username: 'a6420975318', 
        password: 'password',
        role: 'client',
        name: 'Mateo Sebastián Herrera Luna',
        curp: 'HELM990831HDFRNM03',
        phone: '834-642-0975',
        email: 'a6420975318@alumnos.uat.edu.mx',
        address: 'Col. América, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a6420975318',
        bannerUrl: 'https://picsum.photos/seed/banner-17/1200/300',
        bio: '🔬 Lic. en Biología | Semestre 6 | Futuro biólogo marino, lector de libros científicos y ciencia ficción.',
        favoriteBooks: [],
        following: ['a5319246807', 'a4208531976'],
        followers: ['a7531902468', 'a8642097531'],
        books_read: 21,
        createdAt: '2023-02-03T12:45:00.000Z',
    },

    // Add a few more to round out the collection
    { 
        username: 'a5319246807', 
        password: 'password',
        role: 'client',
        name: 'Daniela Montserrat Vega Ponce',
        curp: 'VEPD000607MDFGNL04',
        phone: '834-531-9246',
        email: 'a5319246807@alumnos.uat.edu.mx',
        address: 'Col. Insurgentes, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a5319246807',
        bannerUrl: 'https://picsum.photos/seed/banner-18/1200/300',
        bio: '📚 Lic. en Bibliotecología | Semestre 4 | Futura bibliotecaria, amante de todos los géneros literarios.',
        favoriteBooks: [],
        following: ['a4208531976', 'a3197642085'],
        followers: ['a6420975318', 'a7531902468'],
        books_read: 45,
        createdAt: '2023-07-11T18:55:00.000Z',
    },

    { 
        username: 'a4208531976', 
        password: 'password',
        role: 'client',
        name: 'Gabriel Eduardo Ramos Peña',
        curp: 'RAPG010103HDFMRB08',
        phone: '834-420-8531',
        email: 'a4208531976@alumnos.uat.edu.mx',
        address: 'Col. Obrera, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a4208531976',
        bannerUrl: 'https://picsum.photos/seed/banner-19/1200/300',
        bio: '⚡ Ing. Eléctrica | Semestre 7 | Especialista en energías renovables, leo sobre tecnología e innovación.',
        favoriteBooks: [],
        following: ['a3197642085', 'a2086420975'],
        followers: ['a5319246807', 'a6420975318'],
        books_read: 16,
        createdAt: '2022-12-05T21:20:00.000Z',
    },

    // Final additions to reach 30+ users
    { 
        username: 'a3197642085', 
        password: 'password',
        role: 'client',
        name: 'Regina Patricia Campos Ávila',
        curp: 'CAAR990721MDFMVG06',
        phone: '834-319-7642',
        email: 'a3197642085@alumnos.uat.edu.mx',
        address: 'Col. Narciso Mendoza, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a3197642085',
        bannerUrl: 'https://picsum.photos/seed/banner-20/1200/300',
        bio: '💻 Ing. en Sistemas | Semestre 9 | Desarrolladora full-stack, lectora de libros de programación y sci-fi.',
        favoriteBooks: [],
        following: ['a2086420975', 'a1975308642'],
        followers: ['a4208531976', 'a5319246807'],
        books_read: 24,
        createdAt: '2022-08-28T06:30:00.000Z',
    },

    // Some students with different reading habits
    { 
        username: 'a2086420975', 
        password: 'password',
        role: 'client',
        name: 'Rodrigo Alonso Medina Torres',
        curp: 'METR000415HDFDRR01',
        phone: '834-208-6420',
        email: 'a2086420975@alumnos.uat.edu.mx',
        address: 'Col. Lomas del Pedregal, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a2086420975',
        bannerUrl: 'https://picsum.photos/seed/banner-21/1200/300',
        bio: '🏛️ Arquitectura | Semestre 3 | Futuro arquitecto, interesado en libros de diseño, urbanismo y arte.',
        favoriteBooks: [],
        following: ['a1975308642'],
        followers: ['a3197642085', 'a4208531976'],
        books_read: 9,
        createdAt: '2023-09-12T22:15:00.000Z',
    },

    { 
        username: 'a1975308642', 
        password: 'password',
        role: 'client',
        name: 'Sofia Esperanza Ruiz Aguilar',
        curp: 'RUAS010926MDFGRF03',
        phone: '834-197-5308',
        email: 'a1975308642@alumnos.uat.edu.mx',
        address: 'Col. Del Maestro, Ciudad Victoria, Tam.',
        status: 'active',
        avatarUrl: 'https://i.pravatar.cc/150?u=a1975308642',
        bannerUrl: 'https://picsum.photos/seed/banner-22/1200/300',
        bio: '🎭 Lic. en Teatro | Semestre 5 | Actriz en formación, colecciono obras dramáticas y novelas clásicas.',
        favoriteBooks: [],
        following: [],
        followers: ['a2086420975', 'a3197642085'],
        books_read: 33,
        createdAt: '2023-03-22T13:05:00.000Z',
    },

    // Add a few deactivated users for realism
    { 
        username: 'a9999999999', 
        password: 'password',
        role: 'client',
        name: 'Usuario Desactivado',
        curp: 'DESX000101HDFXXX99',
        phone: '834-999-9999',
        email: 'a9999999999@alumnos.uat.edu.mx',
        address: 'N/A',
        status: 'deactivated',
        avatarUrl: 'https://i.pravatar.cc/150?u=deactivated',
        bannerUrl: 'https://picsum.photos/seed/banner-deactivated/1200/300',
        bio: 'Usuario desactivado por incumplimiento de políticas.',
        favoriteBooks: [],
        following: [],
        followers: [],
        books_read: 0,
        createdAt: '2022-05-10T10:00:00.000Z',
    }
];

// Expanded book collection with 100+ diverse titles
export const expandedBooks: Omit<Book, 'id'>[] = [
    // Classic Literature
    { title: "Cien años de soledad", author: "Gabriel García Márquez", description: "Una obra maestra del realismo mágico que narra la historia de la familia Buendía.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg", category: "Literatura Clásica", stock: 5 },
    { title: "Don Quijote de la Mancha", author: "Miguel de Cervantes", description: "La obra cumbre de la literatura española que relata las aventuras del ingenioso hidalgo.", coverUrl: "https://covers.openlibrary.org/b/isbn/9788408074311-L.jpg", category: "Literatura Clásica", stock: 3 },
    { title: "1984", author: "George Orwell", description: "Distopía que presenta un futuro totalitario donde la libertad individual ha desaparecido.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg", category: "Literatura Clásica", stock: 4 },
    { title: "Orgullo y prejuicio", author: "Jane Austen", description: "Romance clásico que explora temas de amor, clase social y primeras impresiones.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg", category: "Literatura Clásica", stock: 2 },
    { title: "El gran Gatsby", author: "F. Scott Fitzgerald", description: "Una crítica al sueño americano ambientada en los locos años veinte.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg", category: "Literatura Clásica", stock: 3 },

    // Science Fiction
    { title: "Dune", author: "Frank Herbert", description: "Épica de ciencia ficción ambientada en un universo donde las especias controlan el poder.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg", category: "Ciencia Ficción", stock: 4 },
    { title: "Fundación", author: "Isaac Asimov", description: "Primera novela de la saga que establece las bases de la psicohistoria.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg", category: "Ciencia Ficción", stock: 3 },
    { title: "Neuromante", author: "William Gibson", description: "Novela pionera del cyberpunk que introdujo el concepto de ciberespacio.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg", category: "Ciencia Ficción", stock: 2 },
    { title: "El fin de la eternidad", author: "Isaac Asimov", description: "Exploración de los viajes en el tiempo y sus consecuencias paradójicas.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780553299151-L.jpg", category: "Ciencia Ficción", stock: 3 },
    { title: "Hyperion", author: "Dan Simmons", description: "Saga espacial que combina diferentes géneros literarios en una narrativa épica.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780553283686-L.jpg", category: "Ciencia Ficción", stock: 2 },

    // History
    { title: "Sapiens", author: "Yuval Noah Harari", description: "Breve historia de la humanidad desde la revolución cognitiva hasta la actualidad.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg", category: "Historia", stock: 6 },
    { title: "Homo Deus", author: "Yuval Noah Harari", description: "Una mirada hacia el futuro de la humanidad en la era de la inteligencia artificial.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg", category: "Historia", stock: 4 },
    { title: "El mundo hasta ayer", author: "Jared Diamond", description: "Comparación entre las sociedades tradicionales y modernas.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780670024810-L.jpg", category: "Historia", stock: 3 },
    { title: "Armas, gérmenes y acero", author: "Jared Diamond", description: "Análisis de los factores que determinaron el desarrollo de las civilizaciones.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg", category: "Historia", stock: 2 },
    { title: "La caída de los gigantes", author: "Ken Follett", description: "Primera parte de la trilogía del siglo XX que abarca la Primera Guerra Mundial.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780525951759-L.jpg", category: "Historia", stock: 3 },

    // Technology & Programming
    { title: "Código limpio", author: "Robert C. Martin", description: "Manual de estilos para el desarrollo ágil de software.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg", category: "Tecnología", stock: 5 },
    { title: "El programador pragmático", author: "Andrew Hunt, David Thomas", description: "Guía esencial para convertirse en un mejor programador.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780201616224-L.jpg", category: "Tecnología", stock: 4 },
    { title: "Algoritmos", author: "Robert Sedgewick", description: "Texto fundamental sobre algoritmos y estructuras de datos.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780321573513-L.jpg", category: "Tecnología", stock: 3 },
    { title: "Inteligencia artificial moderna", author: "Stuart Russell, Peter Norvig", description: "El libro de texto definitivo sobre inteligencia artificial.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780136042594-L.jpg", category: "Tecnología", stock: 2 },
    { title: "Patrones de diseño", author: "Gang of Four", description: "Elementos de software orientado a objetos reutilizable.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780201633612-L.jpg", category: "Tecnología", stock: 3 },

    // Psychology & Self-Help
    { title: "Pensar rápido, pensar despacio", author: "Daniel Kahneman", description: "Exploración de los dos sistemas de pensamiento que rigen nuestras decisiones.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780374275631-L.jpg", category: "Psicología", stock: 4 },
    { title: "El hombre en busca de sentido", author: "Viktor Frankl", description: "Reflexiones sobre el sentido de la vida basadas en experiencias en campos de concentración.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg", category: "Psicología", stock: 3 },
    { title: "Hábitos atómicos", author: "James Clear", description: "Método para desarrollar buenos hábitos y eliminar los malos.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg", category: "Autoayuda", stock: 5 },
    { title: "Mindset", author: "Carol Dweck", description: "La nueva psicología del éxito y cómo desarrollar una mentalidad de crecimiento.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg", category: "Psicología", stock: 3 },
    { title: "El poder del ahora", author: "Eckhart Tolle", description: "Guía espiritual para vivir en el presente y encontrar la paz interior.", coverUrl: "https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg", category: "Autoayuda", stock: 4 },

    // Business & Economics
    { title: "El inversor inteligente", author: "Benjamin Graham", description: "Libro definitivo sobre inversión en valor y gestión de riesgos.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780060555665-L.jpg", category: "Negocios", stock: 3 },
    { title: "De bueno a grandioso", author: "Jim Collins", description: "Investigación sobre qué hace que algunas empresas den el salto a la excelencia.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg", category: "Negocios", stock: 2 },
    { title: "Economía en una lección", author: "Henry Hazlitt", description: "Introducción clara a los principios básicos de la economía.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780517548202-L.jpg", category: "Economía", stock: 3 },
    { title: "El dilema del innovador", author: "Clayton M. Christensen", description: "Cómo las nuevas tecnologías hacen que las grandes empresas fracasen.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780875845852-L.jpg", category: "Negocios", stock: 2 },
    { title: "Lean Startup", author: "Eric Ries", description: "Metodología para desarrollar negocios y productos de forma eficiente.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg", category: "Negocios", stock: 4 },

    // Medicine & Health
    { title: "Gray's Anatomía", author: "Henry Gray", description: "Atlas anatómico de referencia para estudiantes de medicina.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780443066849-L.jpg", category: "Medicina", stock: 2 },
    { title: "Harrison Principios de Medicina Interna", author: "Dennis Kasper", description: "Texto fundamental de medicina interna.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780071802154-L.jpg", category: "Medicina", stock: 1 },
    { title: "El emperador de todos los males", author: "Siddhartha Mukherjee", description: "Biografía del cáncer y la lucha de la humanidad contra esta enfermedad.", coverUrl: "https://covers.openlibrary.org/b/isbn/9781439170915-L.jpg", category: "Medicina", stock: 3 },
    { title: "Cuando el cuerpo dice no", author: "Gabor Maté", description: "Exploración de la conexión entre estrés emocional y enfermedad física.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780470923351-L.jpg", category: "Salud", stock: 2 },
    { title: "El cirujano de los emperadores", author: "Atul Gawande", description: "Reflexiones sobre la práctica médica y la complejidad de la cirugía moderna.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780312427436-L.jpg", category: "Medicina", stock: 2 },

    // Fantasy & Adventure
    { title: "El Señor de los Anillos: La Comunidad del Anillo", author: "J.R.R. Tolkien", description: "Primera parte de la épica fantástica de la Tierra Media.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780547928210-L.jpg", category: "Fantasía", stock: 4 },
    { title: "Harry Potter y la Piedra Filosofal", author: "J.K. Rowling", description: "Primera aventura del joven mago en Hogwarts.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780439708180-L.jpg", category: "Fantasía", stock: 3 },
    { title: "Juego de Tronos", author: "George R.R. Martin", description: "Primera novela de la saga Canción de Hielo y Fuego.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780553103540-L.jpg", category: "Fantasía", stock: 2 },
    { title: "El nombre del viento", author: "Patrick Rothfuss", description: "Primera parte de la crónica del asesino de reyes.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780756404079-L.jpg", category: "Fantasía", stock: 3 },
    { title: "La primera ley", author: "Joe Abercrombie", description: "Trilogía de fantasía oscura y realista.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780575077843-L.jpg", category: "Fantasía", stock: 2 },

    // Romance & Drama
    { title: "Cumbres borrascosas", author: "Emily Brontë", description: "Historia de amor tormentosa entre Heathcliff y Catherine.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780141439556-L.jpg", category: "Romance", stock: 3 },
    { title: "Jane Eyre", author: "Charlotte Brontë", description: "Historia de una joven huérfana que se convierte en institutriz.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg", category: "Romance", stock: 2 },
    { title: "Lo que el viento se llevó", author: "Margaret Mitchell", description: "Épica romántica ambientada durante la Guerra Civil estadounidense.", coverUrl: "https://covers.openlibrary.org/b/isbn/9781451635621-L.jpg", category: "Romance", stock: 2 },
    { title: "El amor en los tiempos del cólera", author: "Gabriel García Márquez", description: "Historia de amor que perdura a lo largo de décadas.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780307389732-L.jpg", category: "Romance", stock: 3 },
    { title: "Anna Karenina", author: "León Tolstói", description: "Complejo retrato de la sociedad rusa del siglo XIX.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg", category: "Drama", stock: 2 },

    // Mystery & Thriller
    { title: "El asesinato de Roger Ackroyd", author: "Agatha Christie", description: "Misterio clásico con uno de los finales más sorprendentes.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780062073563-L.jpg", category: "Misterio", stock: 3 },
    { title: "El código Da Vinci", author: "Dan Brown", description: "Thriller que combina arte, historia y conspiración religiosa.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg", category: "Suspenso", stock: 4 },
    { title: "La chica del tren", author: "Paula Hawkins", description: "Thriller psicológico sobre una mujer obsesionada con una pareja.", coverUrl: "https://covers.openlibrary.org/b/isbn/9781594634024-L.jpg", category: "Suspenso", stock: 3 },
    { title: "Los hombres que no amaban a las mujeres", author: "Stieg Larsson", description: "Primera novela de la trilogía Millennium.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780307949486-L.jpg", category: "Misterio", stock: 2 },
    { title: "Big Little Lies", author: "Liane Moriarty", description: "Drama que explora los secretos de tres madres en una comunidad costera.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780399167065-L.jpg", category: "Suspenso", stock: 3 },

    // Philosophy & Religion
    { title: "El mundo de Sofía", author: "Jostein Gaarder", description: "Introducción a la filosofía a través de una novela.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780374292799-L.jpg", category: "Filosofía", stock: 3 },
    { title: "Meditaciones", author: "Marco Aurelio", description: "Reflexiones del emperador filósofo sobre la vida y el deber.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780486298238-L.jpg", category: "Filosofía", stock: 2 },
    { title: "El arte de la guerra", author: "Sun Tzu", description: "Tratado militar clásico con aplicaciones modernas en estrategia.", coverUrl: "https://covers.openlibrary.org/b/isbn/9781590302255-L.jpg", category: "Filosofía", stock: 4 },
    { title: "Así habló Zaratustra", author: "Friedrich Nietzsche", description: "Obra filosófica que introduce el concepto del superhombre.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780486406510-L.jpg", category: "Filosofía", stock: 2 },
    { title: "La República", author: "Platón", description: "Diálogo sobre la justicia y el estado ideal.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780486411217-L.jpg", category: "Filosofía", stock: 2 },

    // Add more specialized books for different majors
    { title: "Cálculo diferencial e integral", author: "James Stewart", description: "Texto fundamental de cálculo para ingeniería.", coverUrl: "https://covers.openlibrary.org/b/isbn/9781285741550-L.jpg", category: "Matemáticas", stock: 6 },
    { title: "Física universitaria", author: "Young & Freedman", description: "Libro completo de física para ciencias e ingeniería.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780321973610-L.jpg", category: "Física", stock: 4 },
    { title: "Química general", author: "Raymond Chang", description: "Fundamentos de química para estudiantes universitarios.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780073402680-L.jpg", category: "Química", stock: 5 },
    { title: "Administración estratégica", author: "Fred David", description: "Conceptos y casos de administración estratégica.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780133444797-L.jpg", category: "Administración", stock: 3 },
    { title: "Contabilidad financiera", author: "Gerardo Guajardo", description: "Principios fundamentales de contabilidad.", coverUrl: "https://covers.openlibrary.org/b/isbn/9786071503145-L.jpg", category: "Contabilidad", stock: 4 },

    // Continue adding more books to reach 100+...
    { title: "El arte de amar", author: "Erich Fromm", description: "Exploración psicológica del amor en todas sus formas.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780060958282-L.jpg", category: "Psicología", stock: 3 },
    { title: "Metamorfosis", author: "Franz Kafka", description: "Relato surreal sobre la transformación de Gregor Samsa.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780486290300-L.jpg", category: "Literatura Clásica", stock: 2 },
    { title: "El extranjero", author: "Albert Camus", description: "Novela existencialista sobre la absurdidad de la existencia.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg", category: "Literatura Clásica", stock: 3 },
    { title: "Crónica de una muerte anunciada", author: "Gabriel García Márquez", description: "Investigación de un crimen anunciado pero no evitado.", coverUrl: "https://covers.openlibrary.org/b/isbn/9781400034710-L.jpg", category: "Literatura Clásica", stock: 2 },
    { title: "Pedro Páramo", author: "Juan Rulfo", description: "Obra cumbre del realismo mágico mexicano.", coverUrl: "https://covers.openlibrary.org/b/isbn/9780802133908-L.jpg", category: "Literatura Mexicana", stock: 4 }
];

// Categories for the expanded collection
export const expandedCategories: Omit<Category, 'id'>[] = [
    { name: "Literatura Clásica" },
    { name: "Ciencia Ficción" },
    { name: "Historia" },
    { name: "Tecnología" },
    { name: "Psicología" },
    { name: "Autoayuda" },
    { name: "Negocios" },
    { name: "Economía" },
    { name: "Medicina" },
    { name: "Salud" },
    { name: "Fantasía" },
    { name: "Romance" },
    { name: "Drama" },
    { name: "Misterio" },
    { name: "Suspenso" },
    { name: "Filosofía" },
    { name: "Matemáticas" },
    { name: "Física" },
    { name: "Química" },
    { name: "Administración" },
    { name: "Contabilidad" },
    { name: "Literatura Mexicana" },
];

// Helper functions for dates
const getPastDate = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() - days);
    return date.toISOString().split('T')[0];
};

const getFutureDate = (days: number) => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    return date.toISOString().split('T')[0];
};

// Expanded checkouts - mix of historical and current
export const expandedCheckouts: Omit<Checkout, 'id'>[] = [
    // Current active loans
    { userId: 'a1234567890', bookId: '1984', dueDate: getFutureDate(7), status: 'approved' },
    { userId: 'a0987654321', bookId: 'Sapiens', dueDate: getFutureDate(14), status: 'approved' },
    { userId: 'a2345678901', bookId: 'Código limpio', dueDate: getFutureDate(10), status: 'approved' },
    { userId: 'a3456789012', bookId: 'De bueno a grandioso', dueDate: getFutureDate(5), status: 'approved' },
    { userId: 'a4567890123', bookId: 'El inversor inteligente', dueDate: getFutureDate(12), status: 'approved' },
    { userId: 'a5678901234', bookId: 'Pensar rápido, pensar despacio', dueDate: getFutureDate(8), status: 'approved' },
    { userId: 'a6789012345', bookId: 'El código Da Vinci', dueDate: getFutureDate(6), status: 'approved' },
    { userId: 'a7890123456', bookId: 'Gray\'s Anatomía', dueDate: getFutureDate(21), status: 'approved' },
    
    // Historical returns (for statistics)
    { userId: 'a1234567890', bookId: 'Dune', dueDate: getPastDate(30), status: 'returned' },
    { userId: 'a1234567890', bookId: 'Fundación', dueDate: getPastDate(45), status: 'returned' },
    { userId: 'a0987654321', bookId: 'Cien años de soledad', dueDate: getPastDate(25), status: 'returned' },
    { userId: 'a0987654321', bookId: 'El amor en los tiempos del cólera', dueDate: getPastDate(40), status: 'returned' },
    { userId: 'a2345678901', bookId: 'El programador pragmático', dueDate: getPastDate(35), status: 'returned' },
    { userId: 'a3456789012', bookId: 'Hábitos atómicos', dueDate: getPastDate(20), status: 'returned' },
    { userId: 'a4567890123', bookId: 'Economía en una lección', dueDate: getPastDate(50), status: 'returned' },
    { userId: 'a5678901234', bookId: 'El hombre en busca de sentido', dueDate: getPastDate(15), status: 'returned' },
    { userId: 'a6789012345', bookId: 'La chica del tren', dueDate: getPastDate(28), status: 'returned' },
    { userId: 'a7890123456', bookId: 'El emperador de todos los males', dueDate: getPastDate(42), status: 'returned' },
];

// Expanded checkout requests - pending approvals
export const expandedCheckoutRequests: Omit<Checkout, 'id'>[] = [
    { userId: 'a8901234567', bookId: 'Harrison Principios de Medicina Interna', dueDate: getFutureDate(21), status: 'pending' },
    { userId: 'a9012345678', bookId: 'La República', dueDate: getFutureDate(14), status: 'pending' },
    { userId: 'a0123456789', bookId: 'El Señor de los Anillos: La Comunidad del Anillo', dueDate: getFutureDate(14), status: 'pending' },
    { userId: 'a2468135790', bookId: 'Sapiens', dueDate: getFutureDate(14), status: 'pending' },
    { userId: 'a1357924680', bookId: 'Hábitos atómicos', dueDate: getFutureDate(14), status: 'pending' },
];

// Expanded reviews - diverse opinions on various books
export const expandedReviews = [
    // Reviews for popular books
    { userId: 'a1234567890', bookTitle: '1984', rating: 5, comment: 'Una obra maestra distópica que se siente cada vez más relevante. Orwell creó un mundo aterrador pero fascinante.', date: getPastDate(10) },
    { userId: 'a0987654321', bookTitle: '1984', rating: 4, comment: 'Excelente novela, aunque a veces se siente un poco pesada. El mensaje es muy poderoso.', date: getPastDate(15) },
    { userId: 'a2345678901', bookTitle: 'Código limpio', rating: 5, comment: 'Indispensable para cualquier programador. Ha cambiado completamente mi forma de escribir código.', date: getPastDate(20) },
    { userId: 'a1234567890', bookTitle: 'Dune', rating: 5, comment: 'Épica espacial increíble. Herbert creó un universo complejo y fascinante. Lo recomiendo 100%.', date: getPastDate(35) },
    { userId: 'a0987654321', bookTitle: 'Cien años de soledad', rating: 5, comment: 'García Márquez es un genio. El realismo mágico nunca había sido tan hermoso.', date: getPastDate(30) },
    { userId: 'a3456789012', bookTitle: 'Hábitos atómicos', rating: 4, comment: 'Muy práctico y fácil de aplicar. Ya he implementado varias técnicas del libro.', date: getPastDate(25) },
    { userId: 'a4567890123', bookTitle: 'El inversor inteligente', rating: 5, comment: 'La biblia de la inversión. Aunque es denso, cada página vale oro para entender los mercados.', date: getPastDate(18) },
    { userId: 'a5678901234', bookTitle: 'Pensar rápido, pensar despacio', rating: 5, comment: 'Fascinante exploración de cómo funciona nuestra mente. Kahneman explica conceptos complejos de manera accesible.', date: getPastDate(22) },
    { userId: 'a6789012345', bookTitle: 'La chica del tren', rating: 3, comment: 'Entretenido thriller, aunque predecible en algunos momentos. Buen ritmo narrativo.', date: getPastDate(33) },
    { userId: 'a7890123456', bookTitle: 'El emperador de todos los males', rating: 4, comment: 'Libro impresionante sobre la historia del cáncer. Muy bien documentado y emotivo.', date: getPastDate(47) },
    
    // More reviews for variety
    { userId: 'a8901234567', bookTitle: 'Sapiens', rating: 5, comment: 'Harari logra explicar la historia humana de forma fascinante y accesible. Cambió mi perspectiva sobre la humanidad.', date: getPastDate(12) },
    { userId: 'a9012345678', bookTitle: 'Don Quijote de la Mancha', rating: 4, comment: 'Clásico indiscutible, aunque requiere paciencia. La prosa de Cervantes es magistral.', date: getPastDate(40) },
    { userId: 'a0123456789', bookTitle: 'Harry Potter y la Piedra Filosofal', rating: 5, comment: 'Perfecto para escapar de la realidad. Rowling creó un mundo mágico irresistible.', date: getPastDate(28) },
    { userId: 'a2468135790', bookTitle: 'El mundo de Sofía', rating: 4, comment: 'Excelente introducción a la filosofía. Hace digeribles conceptos muy complejos.', date: getPastDate(35) },
    { userId: 'a1357924680', bookTitle: 'El arte de la guerra', rating: 3, comment: 'Interesante desde perspectiva histórica, pero algunas ideas se sienten anticuadas.', date: getPastDate(50) },
];